#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from collections import OrderedDict
from pathlib import Path

from dotenv import dotenv_values

PROFILE_NAMES = ("mac", "cloud", "asterisk")
ENV_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def load_env_file(path: Path) -> OrderedDict[str, str]:
    values = dotenv_values(path)
    loaded: OrderedDict[str, str] = OrderedDict()
    for key, value in values.items():
        if key is None or value is None:
            continue
        if not ENV_KEY_RE.match(key):
            raise ValueError(f"Invalid env key in {path}: {key}")
        loaded[key] = str(value)
    return loaded


def merge_env_files(paths: list[Path]) -> OrderedDict[str, str]:
    merged: OrderedDict[str, str] = OrderedDict()
    for path in paths:
        for key, value in load_env_file(path).items():
            if key in merged:
                del merged[key]
            merged[key] = value
    return merged


def write_env_file(path: Path, values: OrderedDict[str, str], *, profile: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        file.write(
            "# Generated by scripts/build_env.py. Do not commit real secrets.\n"
        )
        file.write(f"# profile={profile}\n\n")
        for key, value in values.items():
            file.write(f"{key}={value}\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build one flat runtime env from shared and profile templates."
    )
    parser.add_argument(
        "--profile",
        choices=PROFILE_NAMES,
        required=True,
        help="Deployment profile to build.",
    )
    parser.add_argument(
        "--secrets",
        action="append",
        default=[],
        help="Optional ignored env file with real secrets. Can be repeated.",
    )
    parser.add_argument(
        "--output",
        default=".env.local",
        help="Output env file path. Default: .env.local",
    )
    parser.add_argument(
        "--print-keys",
        action="store_true",
        help="Print generated keys without values.",
    )
    args = parser.parse_args()

    project_dir = Path(__file__).resolve().parent.parent
    env_dir = project_dir / "env"
    paths = [
        env_dir / "common.env.example",
        env_dir / f"{args.profile}.env.example",
    ]
    paths.extend(Path(item).expanduser() for item in args.secrets)

    missing = [path for path in paths if not path.exists()]
    if missing:
        missing_text = ", ".join(str(path) for path in missing)
        raise FileNotFoundError(f"Env file not found: {missing_text}")

    values = merge_env_files(paths)
    output_path = Path(args.output).expanduser()
    if not output_path.is_absolute():
        output_path = project_dir / output_path
    write_env_file(output_path, values, profile=args.profile)

    print(f"Wrote {len(values)} keys to {output_path}")
    if args.print_keys:
        for key in values:
            print(key)


if __name__ == "__main__":
    main()
