# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sber_salutespeech_proto/synthesis/v1/synthesis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sber_salutespeech_proto/synthesis/v1/synthesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4sber_salutespeech_proto/synthesis/v1/synthesis.proto\x12\x18smartspeech.synthesis.v1\x1a\x1egoogle/protobuf/duration.proto\"\xee\x02\n\x10SynthesisRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12P\n\x0e\x61udio_encoding\x18\x02 \x01(\x0e\x32\x38.smartspeech.synthesis.v1.SynthesisRequest.AudioEncoding\x12\x10\n\x08language\x18\x03 \x01(\t\x12L\n\x0c\x63ontent_type\x18\x04 \x01(\x0e\x32\x36.smartspeech.synthesis.v1.SynthesisRequest.ContentType\x12\r\n\x05voice\x18\x05 \x01(\t\x12\x15\n\rrebuild_cache\x18\x06 \x01(\x08\"Q\n\rAudioEncoding\x12\x1e\n\x1a\x41UDIO_ENCODING_UNSPECIFIED\x10\x00\x12\r\n\tPCM_S16LE\x10\x01\x12\x08\n\x04OPUS\x10\x02\x12\x07\n\x03WAV\x10\x03\"!\n\x0b\x43ontentType\x12\x08\n\x04TEXT\x10\x00\x12\x08\n\x04SSML\x10\x01\"T\n\x11SynthesisResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x31\n\x0e\x61udio_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration2v\n\x0bSmartSpeech\x12g\n\nSynthesize\x12*.smartspeech.synthesis.v1.SynthesisRequest\x1a+.smartspeech.synthesis.v1.SynthesisResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sber_salutespeech_proto.synthesis.v1.synthesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESISREQUEST']._serialized_start=115
  _globals['_SYNTHESISREQUEST']._serialized_end=481
  _globals['_SYNTHESISREQUEST_AUDIOENCODING']._serialized_start=365
  _globals['_SYNTHESISREQUEST_AUDIOENCODING']._serialized_end=446
  _globals['_SYNTHESISREQUEST_CONTENTTYPE']._serialized_start=448
  _globals['_SYNTHESISREQUEST_CONTENTTYPE']._serialized_end=481
  _globals['_SYNTHESISRESPONSE']._serialized_start=483
  _globals['_SYNTHESISRESPONSE']._serialized_end=567
  _globals['_SMARTSPEECH']._serialized_start=569
  _globals['_SMARTSPEECH']._serialized_end=687
# @@protoc_insertion_point(module_scope)
